### ISSUE TITLE
Version Semantic and other Bugs in tensorflow_cookbook/09_Recurrent_Neural_Networks/04_Stacking_Multiple_LSTM_Layers/04_stacking_multiple_lstm.py

### ISSUE THREAD

**Issue by ayushtiwariiitk** [nfmcclure/tensorflow_cookbook#81]
In line 136:
self.lstm_cell = tf.contrib.rnn.BasicLSTMCell(rnn_size)
change to 
self.lstm_cell = tf.contrib.rnn.BasicLSTMCell(rnn_size, reuse=tf.get_variable_scope().reuse)

In line 137:
self.lstm_cell = tf.contrib.rnn.MultiRNNCell([self.lstm_cell] * self.num_layers)
change to
self.lstm_cell = tf.contrib.rnn.MultiRNNCell([self.lstm_cell for self.lstm_cell in range(num_layers)])

In line 138:
self.initial_state = self.lstm_cell.zero_state(self.batch_size, tf.float32)

Please help, as I am getting the error:
/core_rnn_cell_impl.py", line 929, in <genexpr>
    return tuple(cell.zero_state(batch_size, dtype) for cell in self._cells)

AttributeError: 'int' object has no attribute 'zero_state'

Or else:

In line 137:
change to
self.lstm_cell = tf.contrib.rnn.MultiRNNCell([self.lstm_cell for _ in range(num_layers)])

Then an error occurs:

self._value = int(value)

TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'

**Comment by nfmcclure** [comment]
Hi @ayushtiwariiitk ,  Thanks for bringing this up. I updated the script to
`self.lstm_cell = tf.contrib.rnn.MultiRNNCell([self.lstm_cell for _ in range(self.num_layers)])`
and it works/runs for me.  Try repulling the repo, and making sure you are running TensorFlow v1.12+ and trying again.  If that doesn't work, please let me know the version numbers of your python 3 and TensorFlow libraries and which operating system you are running on.  Thanks!

**Comment by ayushtiwariiitk** [comment]
Hi @nfmcclure, Thanks for the update.
But, I am still getting some issues.
ValueError: Attempt to reuse RNNCell

My python and tensorflow confg are as follows:
Python 3.5.3 :: Anaconda custom (64-bit)
tf.__version__'1.1.0'

**Comment by nfmcclure** [comment]
Hi @ayushtiwariiitk ,  Sorry for the late response, I only get around to working on this project about once a month.  Please try to update (1) Tensorflow to version 1.2+ and try again.

**Comment by nfmcclure** [comment]
I'm going to close this issue for now.

I'm currently starting to overhaul the code to be compatible for TensorFlow v1.6.  Expect changes to this chapter in the next few months.
